# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Steven De La Fuente
title: Geographic Information Systems Analyst
email: stevendella40@gmail.com
website: steven-delafuente.github.io

darkmode: true

# Social links
#twitter_username: facespics
github_username:  steven-delafuente
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jsteven-delafuente
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Geographic Information Science / Data Analysis professional seeking an opportunity to work with amazing people and become valuable asset to your company. I have experience in ArcGIS, QGIS, RStudio, Python and SQL. I am comfortable working with Linux computer systems and servers. I have an understanding of networking and have deployed database systems and websites in the past. I enjoy developing and manipulating large data sets and I always have a smile on my face.

  I am most skilled in: <mark>Teamwork</mark>, <mark>Python</mark>, and <mark>R</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in quantitative modeling and software engineering some of my other interests and hobbies are:
   - Woodworking
   - Surfing
   - Rock Climbing
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
